<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>7b35a5bc-8b30-4ae6-a293-d2cc60b658da</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Chatly.WebApi\Chatly.WebApi.csproj" />
        <ProjectReference Include="..\Chatly.MigrationService\Chatly.MigrationService.csproj"/>
        <ProjectReference Include="..\Chatly.ServiceDefaults\Chatly.ServiceDefaults.csproj" IsAspireProjectResource="false"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.PostgreSQL"/>
    </ItemGroup>

</Project>
