<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Chatly.Contracts\Chatly.Contracts.csproj"/>
        <ProjectReference Include="..\Chatly.Shared\Chatly.Shared.csproj" />
        <ProjectReference Include="..\Chatly.SourceGenerator\Chatly.SourceGenerator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SIPSorcery"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Chatly.Rtc.Tests" />
    </ItemGroup>

</Project>
