using System.Text;

namespace Chatly.SourceGenerator.Templates;

public static class DependencyInjectionTemplate
{
    private const string RegistrationPlaceholder = "        // __SERVICE_REGISTRATIONS__";

    private const string Template = """
                                    // <auto-generated />
                                    #nullable enable

                                    using Microsoft.Extensions.DependencyInjection;

                                    namespace Chatly.Generated;

                                    public static class GeneratedServicesExtensions
                                    {
                                        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
                                            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                                        {
                                            // __SERVICE_REGISTRATIONS__

                                            return services;
                                        }
                                    }
                                    """;

    public static string Render(
        IEnumerable<(string ImplementationTypeName, string ServiceTypeName, int Lifetime)> services)
    {
        var registrations = new StringBuilder();

        foreach (var service in services
                     .Distinct()
                     .OrderBy(static service => service.ImplementationTypeName, StringComparer.Ordinal)
                     .ThenBy(static service => service.ServiceTypeName, StringComparer.Ordinal))
        {
            var registrationMethod = service.Lifetime switch
            {
                0 => "AddSingleton",
                1 => "AddScoped",
                2 => "AddTransient",
                _ => throw new ArgumentOutOfRangeException(nameof(services), "Unsupported service lifetime.")
            };

            registrations
                .Append("        services.")
                .Append(registrationMethod)
                .Append('<')
                .Append(service.ServiceTypeName);

            if (service.ServiceTypeName != service.ImplementationTypeName)
            {
                registrations
                    .Append(", ")
                    .Append(service.ImplementationTypeName);
            }

            registrations.AppendLine(">();");
        }

        return Template.Replace(RegistrationPlaceholder, registrations.ToString().TrimEnd());
    }
}