using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Chatly.SourceGenerator.Templates;

public static class OptionTemplate
{
    private const string RegistrationPlaceholder = "        // __OPTION_REGISTRATIONS__";

    public const string Template = """
                                   // <auto-generated />
                                   #nullable enable

                                   using Microsoft.Extensions.DependencyInjection;

                                   namespace Chatly.Generated;

                                   public static class GeneratedOptionsExtensions
                                   {
                                       public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedOptions(
                                           this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                                           global::Microsoft.Extensions.Configuration.IConfiguration configuration)
                                       {
                                           // __OPTION_REGISTRATIONS__

                                           return services;
                                       }
                                   }
                                   """;

    public static string Render(IEnumerable<(string TypeName, string SectionName)> options)
    {
        var registrations = new StringBuilder();

        foreach (var option in options.OrderBy(static option => option.TypeName, StringComparer.Ordinal))
        {
            var sectionName = SymbolDisplay.FormatLiteral(option.SectionName, true);

            registrations
                .Append(
                    "        global::Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions<")
                .Append(option.TypeName)
                .AppendLine(">(services)")
                .Append("            .BindConfiguration(")
                .Append(sectionName)
                .AppendLine(")")
                .AppendLine("            .ValidateDataAnnotations()")
                .AppendLine("            .ValidateOnStart();");
        }

        return Template.Replace(RegistrationPlaceholder, registrations.ToString().TrimEnd());
    }
}