<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="Refit"/>
        <PackageReference Include="Testcontainers.Azurite"/>
        <PackageReference Include="Testcontainers.PostgreSql"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Chatly.WebApi\Chatly.WebApi.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="testsettings.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Net"/>
        <Using Include="Chatly.Contracts.Common"/>
        <Using Include="Chatly.WebApi.Common.Infrastructure.Persistence"/>
        <Using Include="Chatly.WebApi.Features.Users.Models"/>
        <Using Include="Chatly.WebApi.IntegrationTests.Factories"/>
        <Using Include="Chatly.WebApi.IntegrationTests.Infrastructure"/>
        <Using Include="Chatly.WebApi.IntegrationTests.Infrastructure.Api"/>
        <Using Include="Chatly.WebApi.IntegrationTests.Infrastructure.Fixtures"/>
        <Using Include="Microsoft.EntityFrameworkCore"/>
        <Using Include="Microsoft.Extensions.DependencyInjection"/>
    </ItemGroup>

</Project>
