<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Headless"/>
        <PackageReference Include="NSubstitute"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Chatly.Desktop/Chatly.Desktop.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="NSubstitute"/>
    </ItemGroup>

</Project>
