using Chatly.SourceGenerator.UnitTests.Tests.DependencyInjection.Infrastructure;

namespace Chatly.SourceGenerator.UnitTests.Tests.DependencyInjection;

public sealed class ServiceRegistrationGeneratorTests
{
    [Fact]
    public void Generator_Should_EmitAllLifetimesOrderedByImplementation_When_ServicesAreDeclared()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              [TransientService]
                              public sealed class ZTransient;

                              [SingletonService]
                              public sealed class ASingleton;

                              [ScopedService]
                              public sealed class MScoped;
                              """;

        var first = GeneratorTestHelper.Run(source);
        var second = GeneratorTestHelper.Run(source);

        var singleton = first.GeneratedSource.IndexOf("services.AddSingleton<global::ASingleton>();", StringComparison.Ordinal);
        var scoped = first.GeneratedSource.IndexOf("services.AddScoped<global::MScoped>();", StringComparison.Ordinal);
        var transient = first.GeneratedSource.IndexOf("services.AddTransient<global::ZTransient>();", StringComparison.Ordinal);
        singleton.Should().BeGreaterThanOrEqualTo(0);
        scoped.Should().BeGreaterThan(singleton);
        transient.Should().BeGreaterThan(scoped);
        second.GeneratedSource.Should().Be(first.GeneratedSource);
        first.GeneratedSource.Should().StartWith("// <auto-generated />\n#nullable enable");
        AssertNoErrors(first);
    }

    [Fact]
    public void Generator_Should_RegisterImplementationOnceAndForwardServiceType_When_AsSelfIsSet()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IService;

                              [ScopedService(typeof(IService), asSelf: true)]
                              public sealed class Service : IService;
                              """;

        var result = GeneratorTestHelper.Run(source);

        result.GeneratedSource.Should().Contain(
            "services.AddScoped<global::IService>(static provider => provider.GetRequiredService<global::Service>());");
        result.GeneratedSource.Should().Contain("services.AddScoped<global::Service>();");
        result.GeneratedSource.Should().NotContain("services.AddScoped<global::IService, global::Service>();");
        AssertNoErrors(result);
    }

    [Fact]
    public void Generator_Should_EmitEveryRegistration_When_ClassHasSeveralServiceAttributes()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IFirst;
                              public interface ISecond;

                              [SingletonService(typeof(IFirst))]
                              [SingletonService(typeof(ISecond))]
                              public sealed class Service : IFirst, ISecond;
                              """;

        var result = GeneratorTestHelper.Run(source);

        result.GeneratedSource.Should().Contain("services.AddSingleton<global::IFirst, global::Service>();");
        result.GeneratedSource.Should().Contain("services.AddSingleton<global::ISecond, global::Service>();");
        AssertNoErrors(result);
    }

    [Fact]
    public void Generator_Should_UseTypeOverload_When_ServiceIsOpenGeneric()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IService<T>;

                              [ScopedService(typeof(IService<>))]
                              public sealed class Service<T> : IService<T>;
                              """;

        var result = GeneratorTestHelper.Run(source);

        result.GeneratedSource.Should().Contain(
            "services.AddScoped(typeof(global::IService<>), typeof(global::Service<>));");
        AssertNoErrors(result);
    }

    [Fact]
    public void Generator_Should_KeepClosedGenericServiceType_When_ServiceIsClosedGeneric()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IService<T>;

                              [ScopedService(typeof(IService<string>))]
                              public sealed class Service : IService<string>;
                              """;

        var result = GeneratorTestHelper.Run(source);

        result.GeneratedSource.Should().Contain(
            "services.AddScoped<global::IService<string>, global::Service>();");
        AssertNoErrors(result);
    }

    [Fact]
    public void Generator_Should_ReportErrorAndOmitRegistration_When_ImplementationIsAbstract()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              [SingletonService]
                              public abstract class Service;
                              """;

        AssertErrorAndOmitted(source, "CHATLYDI001", "global::Service");
    }

    [Fact]
    public void Generator_Should_ReportErrorAndOmitRegistration_When_ServiceTypeIsIncompatible()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IService;

                              [ScopedService(typeof(IService))]
                              public sealed class Service;
                              """;

        AssertErrorAndOmitted(source, "CHATLYDI002", "global::Service");
    }

    [Fact]
    public void Generator_Should_WarnAndEmitOnce_When_RegistrationIsDuplicated()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              [TransientService]
                              [TransientService]
                              public sealed class Service;
                              """;

        var result = GeneratorTestHelper.Run(source);

        result.GeneratorDiagnostics.Should().ContainSingle(static diagnostic => diagnostic.Id == "CHATLYDI003")
            .Which.Severity.Should().Be(DiagnosticSeverity.Warning);
        Count(result.GeneratedSource, "services.AddTransient<global::Service>();").Should().Be(1);
        result.GeneratorDiagnostics.Should().NotContain(static diagnostic => diagnostic.Id == "CS8785");
    }

    [Fact]
    public void Generator_Should_ReportErrorAndOmitRegistration_When_LifetimesConflict()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              [SingletonService]
                              [ScopedService]
                              public sealed class Service;
                              """;

        AssertErrorAndOmitted(source, "CHATLYDI004", "global::Service");
    }

    [Fact]
    public void Generator_Should_ReportErrorAndOmitRegistration_When_AsSelfHasNoServiceType()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              [SingletonService(asSelf: true)]
                              public sealed class Service;
                              """;

        AssertErrorAndOmitted(source, "CHATLYDI005", "global::Service");
    }

    [Fact]
    public void Generator_Should_ReportErrorAndOmitRegistration_When_OpenGenericArityDiffers()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IService<T>;

                              [ScopedService(typeof(IService<>))]
                              public sealed class Service<TFirst, TSecond> : IService<TFirst>;
                              """;

        AssertErrorAndOmitted(source, "CHATLYDI006", "global::Service<,>");
    }

    private static void AssertErrorAndOmitted(string source, string diagnosticId, string omittedText)
    {
        var result = GeneratorTestHelper.Run(source);

        var diagnostic = result.GeneratorDiagnostics.Should()
            .ContainSingle(diagnostic => diagnostic.Id == diagnosticId)
            .Which;
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Error);
        result.GeneratedSource.Should().NotContain(omittedText);
        result.GeneratorDiagnostics.Should().NotContain(static item => item.Id == "CS8785");
    }

    private static void AssertNoErrors(GeneratorTestResult result)
    {
        result.GeneratorDiagnostics.Should().NotContain(
            static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
        result.CompilationDiagnostics.Should().NotContain(
            static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    }

    private static int Count(string value, string search)
    {
        var count = 0;
        var index = 0;

        while ((index = value.IndexOf(search, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += search.Length;
        }

        return count;
    }
}
