namespace Chatly.SourceGenerator.Tests;

public sealed class ServiceRegistrationGeneratorTests
{
    [Fact]
    public void EmitsAllLifetimesInStableOrder()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              [TransientService]
                              public sealed class ZTransient;

                              [SingletonService]
                              public sealed class ASingleton;

                              [ScopedService]
                              public sealed class MScoped;
                              """;

        var first = GeneratorTestHelper.Run(source);
        var second = GeneratorTestHelper.Run(source);

        Assert.Contains("services.AddSingleton<global::ASingleton>();", first.GeneratedSource);
        Assert.Contains("services.AddScoped<global::MScoped>();", first.GeneratedSource);
        Assert.Contains("services.AddTransient<global::ZTransient>();", first.GeneratedSource);
        Assert.Equal(first.GeneratedSource, second.GeneratedSource);
        Assert.StartsWith("// <auto-generated />\n#nullable enable", first.GeneratedSource);
        AssertNoErrors(first);
    }

    [Fact]
    public void EmitsExplicitInterfaceAndAsSelfRegistrations()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IService;

                              [ScopedService(typeof(IService), asSelf: true)]
                              public sealed class Service : IService;
                              """;

        var result = GeneratorTestHelper.Run(source);

        Assert.Contains("services.AddScoped<global::IService, global::Service>();", result.GeneratedSource);
        Assert.Contains("services.AddScoped<global::Service>();", result.GeneratedSource);
        AssertNoErrors(result);
    }

    [Fact]
    public void EmitsMultipleValidServiceAttributes()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IFirst;
                              public interface ISecond;

                              [SingletonService(typeof(IFirst))]
                              [SingletonService(typeof(ISecond))]
                              public sealed class Service : IFirst, ISecond;
                              """;

        var result = GeneratorTestHelper.Run(source);

        Assert.Contains("services.AddSingleton<global::IFirst, global::Service>();", result.GeneratedSource);
        Assert.Contains("services.AddSingleton<global::ISecond, global::Service>();", result.GeneratedSource);
        AssertNoErrors(result);
    }

    [Fact]
    public void EmitsValidOpenGenericRegistrationUsingTypeOverload()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IService<T>;

                              [ScopedService(typeof(IService<>))]
                              public sealed class Service<T> : IService<T>;
                              """;

        var result = GeneratorTestHelper.Run(source);

        Assert.Contains(
            "services.AddScoped(typeof(global::IService<>), typeof(global::Service<>));",
            result.GeneratedSource);
        AssertNoErrors(result);
    }

    [Fact]
    public void PreservesClosedGenericServiceType()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IService<T>;

                              [ScopedService(typeof(IService<string>))]
                              public sealed class Service : IService<string>;
                              """;

        var result = GeneratorTestHelper.Run(source);

        Assert.Contains(
            "services.AddScoped<global::IService<string>, global::Service>();",
            result.GeneratedSource);
        AssertNoErrors(result);
    }

    [Fact]
    public void ReportsAbstractImplementationAndOmitsRegistration()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              [SingletonService]
                              public abstract class Service;
                              """;

        AssertErrorAndOmitted(source, "CHATLYDI001", "global::Service");
    }

    [Fact]
    public void ReportsIncompatibleServiceTypeAndOmitsRegistration()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IService;

                              [ScopedService(typeof(IService))]
                              public sealed class Service;
                              """;

        AssertErrorAndOmitted(source, "CHATLYDI002", "global::Service");
    }

    [Fact]
    public void ReportsDuplicateSameLifetimeAndEmitsOnce()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              [TransientService]
                              [TransientService]
                              public sealed class Service;
                              """;

        var result = GeneratorTestHelper.Run(source);

        Assert.Contains(result.GeneratorDiagnostics, static diagnostic => diagnostic.Id == "CHATLYDI003");
        Assert.Equal(1, Count(result.GeneratedSource, "services.AddTransient<global::Service>();"));
        Assert.DoesNotContain(result.GeneratorDiagnostics, static diagnostic => diagnostic.Id == "CS8785");
    }

    [Fact]
    public void ReportsConflictingLifetimesAndOmitsRegistration()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              [SingletonService]
                              [ScopedService]
                              public sealed class Service;
                              """;

        AssertErrorAndOmitted(source, "CHATLYDI004", "global::Service");
    }

    [Fact]
    public void ReportsAsSelfWithoutExplicitServiceAndOmitsRegistration()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              [SingletonService(asSelf: true)]
                              public sealed class Service;
                              """;

        AssertErrorAndOmitted(source, "CHATLYDI005", "global::Service");
    }

    [Fact]
    public void ReportsOpenGenericArityMismatchAndOmitsRegistration()
    {
        const string source = """
                              using Chatly.DependencyInjection;

                              public interface IService<T>;

                              [ScopedService(typeof(IService<>))]
                              public sealed class Service<TFirst, TSecond> : IService<TFirst>;
                              """;

        AssertErrorAndOmitted(source, "CHATLYDI006", "global::Service<,>");
    }

    private static void AssertErrorAndOmitted(string source, string diagnosticId, string omittedText)
    {
        var result = GeneratorTestHelper.Run(source);

        var diagnostic = Assert.Single(result.GeneratorDiagnostics, diagnostic => diagnostic.Id == diagnosticId);
        Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.DoesNotContain(omittedText, result.GeneratedSource);
        Assert.DoesNotContain(result.GeneratorDiagnostics, static item => item.Id == "CS8785");
    }

    private static void AssertNoErrors(GeneratorTestResult result)
    {
        Assert.DoesNotContain(result.GeneratorDiagnostics,
            static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
        Assert.DoesNotContain(result.CompilationDiagnostics,
            static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    }

    private static int Count(string value, string search)
    {
        var count = 0;
        var index = 0;

        while ((index = value.IndexOf(search, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += search.Length;
        }

        return count;
    }
}