namespace Chatly.SourceGenerator.Generators.Services;

internal static class ServiceAttributesSource
{
    internal const string Text = """
                                 // <auto-generated />
                                 #nullable enable

                                 namespace Chatly.DependencyInjection;

                                 [global::System.AttributeUsage(
                                     global::System.AttributeTargets.Class,
                                     Inherited = false,
                                     AllowMultiple = true)]
                                 [global::System.CodeDom.Compiler.GeneratedCode("Chatly.SourceGenerator", "1.0.0.0")]
                                 public sealed class SingletonServiceAttribute : global::System.Attribute
                                 {
                                     public SingletonServiceAttribute(global::System.Type? serviceType = null, bool asSelf = false)
                                     {
                                     }
                                 }

                                 [global::System.AttributeUsage(
                                     global::System.AttributeTargets.Class,
                                     Inherited = false,
                                     AllowMultiple = true)]
                                 [global::System.CodeDom.Compiler.GeneratedCode("Chatly.SourceGenerator", "1.0.0.0")]
                                 public sealed class ScopedServiceAttribute : global::System.Attribute
                                 {
                                     public ScopedServiceAttribute(global::System.Type? serviceType = null, bool asSelf = false)
                                     {
                                     }
                                 }

                                 [global::System.AttributeUsage(
                                     global::System.AttributeTargets.Class,
                                     Inherited = false,
                                     AllowMultiple = true)]
                                 [global::System.CodeDom.Compiler.GeneratedCode("Chatly.SourceGenerator", "1.0.0.0")]
                                 public sealed class TransientServiceAttribute : global::System.Attribute
                                 {
                                     public TransientServiceAttribute(global::System.Type? serviceType = null, bool asSelf = false)
                                     {
                                     }
                                 }
                                 """;
}