<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Assets\chatly-logo.ico</ApplicationIcon>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AsyncImageLoader.Avalonia"/>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Duende.IdentityModel.OidcClient"/>
        <PackageReference Include="FluentIcons.Avalonia"/>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="NAudio"/>
        <PackageReference Include="SoundFlow"/>
        <PackageReference Include="System.Security.Cryptography.ProtectedData"/>
        <PackageReference Include="Refit"/>
        <PackageReference Include="Refit.HttpClientFactory"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Chatly.Contracts\Chatly.Contracts.csproj"/>
        <ProjectReference Include="..\Chatly.Shared\Chatly.Shared.csproj"/>
        <ProjectReference Include="..\Chatly.SourceGenerator\Chatly.SourceGenerator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="App.axaml.cs">
            <DependentUpon>App.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Popups\PopupOverlayHost.axaml.cs">
            <DependentUpon>PopupOverlayHost.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Popups\OnboardingPopup.axaml.cs">
            <DependentUpon>OnboardingPopup.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Toasts\ToastHostOverlay.axaml.cs">
            <DependentUpon>ToastHostOverlay.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Windows\MainWindow.axaml.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Windows\SplashScreenWindow.axaml.cs">
            <DependentUpon>SplashScreenWindow.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Pages\ChatPage\ChatPage.axaml.cs">
            <DependentUpon>ChatPage.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Pages\UserPage\Popups\AddFriendPopupOverlay.axaml.cs">
            <DependentUpon>AddFriendPopupOverlay.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Pages\UserPage\Tabs\FriendsTabView.axaml.cs">
            <DependentUpon>FriendsTabView.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Pages\UserPage\Tabs\PendingFriendRequestTabPage.axaml.cs">
            <DependentUpon>PendingFriendRequestTabPage.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Pages\UserPage\Tabs\OnlineFriendsTabPage.axaml.cs">
            <DependentUpon>OnlineFriendsTabPage.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Pages\UserPage\Tabs\AllFriendsTabPage.axaml.cs">
            <DependentUpon>AllFriendsTabPage.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Pages\SettingsPage.axaml.cs">
            <DependentUpon>SettingsPage.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Controls\UserAvatar.axaml.cs">
            <DependentUpon>UserAvatar.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Pages\UserPage\UserPage.axaml.cs">
            <DependentUpon>UserPage.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>
</Project>
