<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Azure.Storage.Blobs"/>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="all"/>
        <PackageReference Include="Hangfire"/>
        <PackageReference Include="Hangfire.PostgreSql"/>
        <PackageReference Include="MailKit"/>
        <PackageReference Include="Mediator.Abstractions"/>
        <PackageReference Include="Mediator.SourceGenerator">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Newtonsoft.Json"/>
        <PackageReference Include="Scalar.AspNetCore"/>
        <PackageReference Include="Vogen"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\tools\Chatly.ServiceDefaults\Chatly.ServiceDefaults.csproj"/>
        <ProjectReference Include="..\Chatly.Contracts\Chatly.Contracts.csproj"/>
        <ProjectReference Include="..\Chatly.Shared\Chatly.Shared.csproj"/>
        <ProjectReference Include="..\Chatly.SourceGenerator\Chatly.SourceGenerator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Common/Infrastructure/Email/Templates/*.html">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Chatly.WebApi.UnitTests"/>
        <InternalsVisibleTo Include="Chatly.WebApi.IntegrationTests"/>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Chatly.Contracts.Common"/>
        <Using Include="Chatly.Contracts.Features.Hubs.Abstraction"/>
        <Using Include="Chatly.Contracts.Features.Users.Endpoints.GetCurrentUser"/>
        <Using Include="Chatly.Contracts.Features.Users.Endpoints.GetCurrentUserProfilePicture"/>
        <Using Include="Chatly.Contracts.Features.Users.Endpoints.SearchUsers"/>
        <Using Include="Chatly.DependencyInjection"/>
        <Using Include="Chatly.WebApi.Common.Abstraction"/>
        <Using Include="Chatly.WebApi.Common.Extensions"/>
        <Using Include="Chatly.WebApi.Common.Infrastructure"/>
        <Using Include="Chatly.WebApi.Common.Infrastructure.Persistence"/>
        <Using Include="Chatly.WebApi.Common.Shared.Exceptions"/>
        <Using Include="Chatly.WebApi.Common.Shared.Models"/>
        <Using Include="Chatly.WebApi.Features.Chats.Models"/>
        <Using Include="Chatly.WebApi.Features.Messages.Models"/>
        <Using Include="Chatly.WebApi.Features.Users.Models"/>
        <Using Include="FluentValidation"/>
        <Using Include="JetBrains.Annotations"/>
        <Using Include="Mediator"/>
        <Using Include="Microsoft.AspNetCore.Mvc"/>
        <Using Include="Microsoft.EntityFrameworkCore"/>
        <Using Include="Vogen"/>
    </ItemGroup>

</Project>
