<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Chatly.SourceGenerator/Chatly.SourceGenerator.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Chatly.SourceGenerator.Generators.Services"/>
        <Using Include="Microsoft.CodeAnalysis"/>
        <Using Include="Microsoft.CodeAnalysis.CSharp"/>
        <Using Include="Microsoft.Extensions.DependencyInjection"/>
    </ItemGroup>

</Project>
