<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <NoWarn>$(NoWarn);RS2000;RS2008</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Generators/Options/Options.cs.template"
                          LogicalName="Chatly.SourceGenerator.Templates.Options.cs.template"
                          WithCulture="false"/>
        <EmbeddedResource Include="Generators/Services/Services.cs.template"
                          LogicalName="Chatly.SourceGenerator.Templates.Services.cs.template"
                          WithCulture="false"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Collections.Immutable"/>
        <Using Include="System.Text"/>
        <Using Include="Chatly.SourceGenerator.Generators.Services.Models"/>
        <Using Include="Chatly.SourceGenerator.Templates"/>
        <Using Include="Microsoft.CodeAnalysis"/>
        <Using Include="Microsoft.CodeAnalysis.CSharp.Syntax"/>
        <Using Include="Microsoft.CodeAnalysis.Text"/>
    </ItemGroup>

</Project>
