parent=base
import=common/keycloak
styles=css/chatly.css
kcFormGroupClass=form-group
kcLabelClass=form-label
kcLabelWrapperClass=label-wrapper
kcInputClass=form-input
kcInputGroup=input-group
kcInputErrorMessageClass=input-error
kcFormPasswordVisibilityButtonClass=password-toggle
kcButtonClass=button
kcButtonPrimaryClass=button-primary
kcButtonDefaultClass=button-secondary
kcButtonBlockClass=button-block
kcAlertClass=alert
kcAlertTitleClass=alert-title
